////// AUTH
export const CREATE_SUPER_USER_SUCCESS = 'CREATE_SUPER_USER_SUCCESS'
export const DARKMODE_CONFIG = 'DARKMODE_CONFIG'
export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_LOADED = 'AUTH_LOADED'
export const RELOADE_PAGE = 'RELOADE_PAGE'
export const SET_NEW_IP = 'SET_NEW_IP'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
////// END-AUTH
////// END-ACCOUNT
export const ACCOUNT_LOADING = 'ACCOUNT_LOADING'
export const ACCOUNT_LOADED = 'ACCOUNT_LOADED'
export const GET_ACCOUNT_ID_FOR_DETAIL = 'GET_ACCOUNT_ID_FOR_DETAIL'
export const ACCOUNT_DETAIL = 'ACCOUNT_DETAIL'
export const GET_ACCOUNT_ID_FOR_UPDATE = 'GET_ACCOUNT_ID_FOR_UPDATE'
export const LIST_ACCOUNT = 'LIST_ACCOUNT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const TOKO_DETAIL = 'TOKO_DETAIL'
export const LIST_HISTORY = 'LIST_HISTORY'
export const GET_HISTORY_ID_FOR_DETAIL = 'GET_HISTORY_ID_FOR_DETAIL'
export const HISTORY_DETAIL = 'HISTORY_DETAIL'
export const LIST_QUERY_HISTORY_EXPORT = 'LIST_QUERY_HISTORY_EXPORT'
////// END-ACCOUNT
////// TRANSAKSI
export const TRANSAKSI_LOADING = 'TRANSAKSI_LOADING'
export const TRANSAKSI_LOADED = 'TRANSAKSI_LOADED'
export const CEK_IMPORT_TRANSAKSI = 'CEK_IMPORT_TRANSAKSI'
////// TRANSAKSI
export const ADD_BARANG_TO_TRANSAKSI = 'ADD_BARANG_TO_TRANSAKSI'
export const CHANGE_TRANSAKSI_DETAIL = 'CHANGE_TRANSAKSI_DETAIL'
export const CLEAR_BARANG_IN_TRANSAKSI = 'CLEAR_BARANG_IN_TRANSAKSI'
export const CLEAR_A_BARANG_FROM_TRANSAKSI = 'CLEAR_A_BARANG_FROM_TRANSAKSI'
////// BELANJA
export const ADD_BARANG_TO_BELANJA = 'ADD_BARANG_TO_BELANJA'
export const CHANGE_BELANJA_DETAIL = 'CHANGE_BELANJA_DETAIL'
export const CLEAR_A_BARANG_FROM_BELANJA = 'CLEAR_A_BARANG_FROM_BELANJA'
export const CLEAR_BARANG_IN_BELANJA = 'CLEAR_BARANG_IN_BELANJA'
//////
export const LIST_TRANSAKSI = 'LIST_TRANSAKSI'
export const QUERY_LIST_TRANSAKSI = 'QUERY_LIST_TRANSAKSI'
export const GET_TRANSAKSI_ID_FOR_DETAIL = 'GET_TRANSAKSI_ID_FOR_DETAIL'
export const TRANSAKSI_DETAIL = 'TRANSAKSI_DETAIL'
////// END-TRANSAKSI
////// JENISBARANG
export const JENISBARANG_LOADING = 'JENISBARANG_LOADING'
export const JENISBARANG_LOADED = 'JENISBARANG_LOADED'
export const GET_JENISBARANG_ID_FOR_DETAIL = 'GET_JENISBARANG_ID_FOR_DETAIL'
export const JENISBARANG_DETAIL = 'JENISBARANG_DETAIL'
export const GET_JENISBARANG_ID_FOR_UPDATE = 'GET_JENISBARANG_ID_FOR_UPDATE'
export const JENISBARANG_DELETED = 'JENISBARANG_DELETED'
export const LIST_JENISBARANG = 'LIST_JENISBARANG'
export const LIST_QUERY_JENISBARANG = 'LIST_QUERY_JENISBARANG'
export const CEK_IMPORT_KATAGORIBARANG = 'CEK_IMPORT_KATAGORIBARANG'
export const LIST_QUERY_JENISBARANG_EXPORT = 'LIST_QUERY_JENISBARANG_EXPORT'
////// END-JENISBARANG
////// BARANG
export const BARANG_LOADING = 'BARANG_LOADING'
export const BARANG_LOADED = 'BARANG_LOADED'
export const GET_BARANG_ID_FOR_DETAIL = 'GET_BARANG_ID_FOR_DETAIL'
export const BARANG_DETAIL = 'BARANG_DETAIL'
export const GET_BARANG_ID_FOR_UPDATE = 'GET_BARANG_ID_FOR_UPDATE'
export const BARANG_DELETED = 'BARANG_DELETED'
export const LIST_BARANG = 'LIST_BARANG'
export const LIST_QUERY_BARANG_EXPORT = 'LIST_QUERY_BARANG_EXPORT'
export const CEK_IMPORT_BARANG = 'CEK_IMPORT_BARANG'
////// END-BARANG
////// HELP
export const HELP_LOADING = 'HELP_LOADING'
export const HELP_LOADED = 'HELP_LOADED'
////// HELP-REPORT
export const LIST_INCOMEREPORT_BARANG = 'LIST_INCOMEREPORT_BARANG'
export const LIST_INCOMEREPORT_KEUANGAN = 'LIST_INCOMEREPORT_KEUANGAN'
export const LIST_OUTCOMEREPORT_BARANG = 'LIST_OUTCOMEREPORT_BARANG'
export const LIST_OUTCOMEREPORT_MODAL = 'LIST_OUTCOMEREPORT_MODAL'
////// END-HELP-REPORT
////// HELP-GRAPH
export const LIST_GRAPH_ASET = 'LIST_GRAPH_ASET'
export const LIST_QUERY_GRAPH_ASET = 'LIST_QUERY_GRAPH_ASET'

export const LIST_GRAPH_UANGMASUK = 'LIST_GRAPH_UANGMASUK'
export const LIST_QUERY_GRAPH_UANGMASUK = 'LIST_QUERY_GRAPH_UANGMASUK'
export const LIST_GRAPH_UANGKELUAR = 'LIST_GRAPH_UANGKELUAR'
export const LIST_QUERY_GRAPH_UANGKELUAR = 'LIST_QUERY_GRAPH_UANGKELUAR'
export const LIST_GRAPH_UANGLOSE = 'LIST_GRAPH_UANGLOSE'
export const LIST_QUERY_GRAPH_UANGLOSE = 'LIST_QUERY_GRAPH_UANGLOSE'
export const LIST_GRAPH_INTENSITASTRANSAKSI = 'LIST_GRAPH_INTENSITASTRANSAKSI'
export const LIST_QUERY_GRAPH_INTENSITASTRANSAKSI = 'LIST_QUERY_GRAPH_INTENSITASTRANSAKSI'
export const LIST_GRAPH_INTENSITASBARANGTRANSAKSI = 'LIST_GRAPH_INTENSITASBARANGTRANSAKSI'
export const LIST_QUERY_GRAPH_INTENSITASBARANGTRANSAKSI = 'LIST_QUERY_GRAPH_INTENSITASBARANGTRANSAKSI'
////// END-HELP-GRAPH
////// END-HELP
////// MESSAGES
export const SUCCESS_MESSAGES = 'SUCCESS_MESSAGES'
export const INFO_MESSAGES = 'INFO_MESSAGES'
export const WARNING_MESSAGES = 'WARNING_MESSAGES'
export const ERROR_MESSAGES = 'ERROR_MESSAGES'
export const CLEAN_MESSAGES = 'CLEAN_MESSAGES'
////// END-MESSAGES