////// MASSAGES
export const CREATE_MASSAGES = 'CREATE_MASSAGES'
export const SUCCESS_MASSAGES = 'SUCCESS_MASSAGES'
export const ERROR_MASSAGES = 'ERROR_MASSAGES'
export const WARNING_MASSAGES = 'WARNING_MASSAGES'

////// USER
////// USER-LOGIN
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'//????
////// USER-LOGOUT
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
////// USER-LOAD_USER
export const USER_LOADING = 'USER_LOADING'
export const USER_NOT_LOADING = 'USER_NOT_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const USER_EXPIRED = 'USER_EXPIRED'

////// BIODATA
////// BIODATA-LOADING
export const BIODATA_LOADING = 'BIODATA_LOADING'
export const BIODATA_NOT_LOADING = 'BIODATA_NOT_LOADING'
////// BIODATA-LOAD_DETAIL
export const _BUTTON_DETAIL_VIEW_ = '_BUTTON_DETAIL_VIEW_'
export const BIODATA_DETAIL_LOADED = 'BIODATA_DETAIL_LOADED'
export const BIODATA_ACCOUNT_DETAIL_LOADED = 'BIODATA_ACCOUNT_DETAIL_LOADED'
////// BIODATA-UPDATE_BIODATA
export const _BUTTON_UPDATE_BIODATA_ = '_BUTTON_UPDATE_BIODATA_'
export const BIODATA_UPDATE_DATA_LOADED = 'BIODATA_UPDATE_DATA_LOADED'
export const BIODATA_UPDATED = 'BIODATA_UPDATED'
////// BIODATA-DELETE
export const BIODATA_DELETED = 'BIODATA_DELETED'
////// BIODATA-UPDATE_BIODATA_ACCOUNT
export const _BUTTON_UPDATE_BIODATA_ACCOUNT_ = '_BUTTON_UPDATE_BIODATA_ACCOUNT_'
export const BIODATA_ACCOUNT_UPDATE_DATA_LOADED = 'BIODATA_ACCOUNT_UPDATE_DATA_LOADED'
export const BIODATA_ACCOUNT_UPDATED = 'BIODATA_ACCOUNT_UPDATED'
////// BIODATA-BIODATA.SISWA
export const SISWA_DATA_LOADED = 'SISWA_DATA_LOADED'
////// BIODATA-BIODATA.SISWA-CREATE
export const SISWA_BIODATA_CREATED = 'SISWA_BIODATA_CREATED'
export const SISWA_BIODATA_FAILED_CREATE = 'SISWA_BIODATA_FAILED_CREATE'
export const SISWA_ACCOUNT_CREATED = 'SISWA_ACCOUNT_CREATED'
export const SISWA_ACCOUNT_FAILED_CREATE = 'SISWA_ACCOUNT_FAILED_CREATE'
export const SISWA_FULLY_CREATED = 'SISWA_FULLY_CREATED'
////// BIODATA-BIODATA.STAFF
export const STAFF_DATA_LOADED = 'STAFF_DATA_LOADED'
////// BIODATA-BIODATA.SISWA-CREATE
export const STAFF_BIODATA_CREATED = 'STAFF_BIODATA_CREATED'
export const STAFF_BIODATA_FAILED_CREATE = 'STAFF_BIODATA_FAILED_CREATE'
export const STAFF_ACCOUNT_CREATED = 'STAFF_ACCOUNT_CREATED'
export const STAFF_ACCOUNT_FAILED_CREATE = 'STAFF_ACCOUNT_FAILED_CREATE'
export const STAFF_FULLY_CREATED = 'STAFF_FULLY_CREATED'
////// BIODATA-BIODATA.ADMIN
export const ADMIN_DATA_LOADED = 'ADMIN_DATA_LOADED'
////// BIODATA-BIODATA.ADMIN-CREATE
export const ADMIN_BIODATA_CREATED = 'ADMIN_BIODATA_CREATED'
export const ADMIN_BIODATA_FAILED_CREATE = 'ADMIN_BIODATA_FAILED_CREATE'
export const ADMIN_ACCOUNT_CREATED = 'ADMIN_ACCOUNT_CREATED'
export const ADMIN_ACCOUNT_FAILED_CREATE = 'ADMIN_ACCOUNT_FAILED_CREATE'
export const ADMIN_FULLY_CREATED = 'ADMIN_FULLY_CREATED'
////// BIODATA-BIODATA.ALL
export const ALL_DATA_LOADED = 'ALL_DATA_LOADED'


////// POINT
////// POINT-PELANGGARAN
////// POINT-PELANGGARAN-LOADING
export const PELANGGARAN_LOADING = 'PELANGGARAN_LOADING'
export const PELANGGARAN_NOT_LOADING = 'PELANGGARAN_NOT_LOADING'
////// POINT-PELANGGARAN-LIST_LOADED
export const PELANGGARAN_LIST_DATA_LOADED = 'PELANGGARAN_LIST_DATA_LOADED'
////// POINT-PELANGGARAN-VIEW
export const _BUTTON_PELANGGARAN_DETAIL_VIEW_ = '_BUTTON_PELANGGARAN_DETAIL_VIEW_'
export const PELANGGARAN_DETAIL_LOADED = 'PELANGGARAN_DETAIL_LOADED'
////// POINT-PELANGGARAN-CREATE
export const PELANGGARAN_CREATED = 'PELANGGARAN_CREATED'
////// POINT-PELANGGARAN-UPDATE
export const _BUTTON_PELANGGARAN_UPDATE_ = '_BUTTON_PELANGGARAN_UPDATE_'
export const PELANGGARAN_UPDATE_DATA_LOADED = 'PELANGGARAN_UPDATE_DATA_LOADED'
export const PELANGGARAN_UPDATED = 'PELANGGARAN_UPDATED'
////// POINT-PELANGGARAN-DELETE
export const PELANGGARAN_DELETED = 'PELANGGARAN_DELETED'
////// POINT.POINT
////// POINT.POINT-LOAD
export const POINT_LIST_POINT_LOADED = 'POINT_LIST_POINT_LOADED'
export const POINT_SCORE_LOADED = 'POINT_SCORE_LOADED'
////// POINT.POINTUNCONFIRM
////// POINT.POINTUNCONFIRM-LOAD
export const POINT_POINTUNCONFIRM_LOADED = 'POINT_POINTUNCONFIRM_LOADED'
////// POINT.POINTCONFIRM
////// POINT.POINTCONFIRM-LOAD
export const POINT_POINTCONFIRM_LOADED = 'POINT_POINTCONFIRM_LOADED'
////// POINT.SUBMISSION
////// POINT.SUBMISSION-LOAD-DETAIL
export const _BUTTON_POINT_DETAIL_VIEW_ = '_BUTTON_POINT_DETAIL_VIEW_'
export const POINT_POINTSUBMISSION_DETAIL_LOADED = 'POINT_POINTSUBMISSION_DETAIL_LOADED'
////// POINT.SUBMISSION-CREATE
export const POINT_POINTSUBMISSION_CREATED = 'POINT_POINTSUBMISSION_CREATED'

////// PRESTASI
////// PRESTASI-LOADING
export const PRESTASI_LOADING = 'PRESTASI_LOADING'
export const PRESTASI_NOT_LOADING = 'PRESTASI_NOT_LOADING'
////// PRESTASI.INSTANSI
////// PRESTASI.INSTANSI-LIST_LOADED
export const INSTANSI_LIST_DATA_LOADED = 'INSTANSI_LIST_DATA_LOADED'
////// PRESTASI.INSTANSI-VIEW
export const _BUTTON_INSTANSI_DETAIL_VIEW_ = '_BUTTON_INSTANSI_DETAIL_VIEW_'
export const INSTANSI_DETAIL_LOADED = 'INSTANSI_DETAIL_LOADED'
////// PRESTASI.INSTANSI-CREATE
export const INSTANSI_CREATED = 'INSTANSI_CREATED'
////// PRESTASI.INSTANSI-UPDATE
export const _BUTTON_INSTANSI_UPDATE_ = '_BUTTON_INSTANSI_UPDATE_'
export const INSTANSI_UPDATE_DATA_LOADED = 'INSTANSI_UPDATE_DATA_LOADED'
export const INSTANSI_UPDATED = 'INSTANSI_UPDATED'
////// PRESTASI.INSTANSI-DELETE
export const INSTANSI_DELETED = 'INSTANSI_DELETED'
////// PRESTASI.PRESTASI
////// PRESTASI.PRESTASI-LOAD
export const PRESTASI_LIST_PRESTASI_LOADED = 'PRESTASI_LIST_PRESTASI_LOADED'
export const PRESTASI_SCORE_LOADED = 'PRESTASI_SCORE_LOADED'
////// PRESTASI.PRESTASIUNCONFIRM
////// PRESTASI.PRESTASIUNCONFIRM-LOAD
export const PRESTASI_PRESTASIUNCONFIRM_LOADED = 'PRESTASI_PRESTASIUNCONFIRM_LOADED'
////// PRESTASI.PRESTASICONFIRM
////// PRESTASI.PRESTASICONFIRM-LOAD
export const PRESTASI_PRESTASICONFIRM_LOADED = 'PRESTASI_PRESTASICONFIRM_LOADED'
////// PRESTASI.SUBMISSION
////// PRESTASI.SUBMISSION-LOAD-DETAIL
export const _BUTTON_PRESTASI_DETAIL_VIEW_ = '_BUTTON_PRESTASI_DETAIL_VIEW_'
export const PRESTASI_PRESTASISUBMISSION_DETAIL_LOADED = 'PRESTASI_PRESTASISUBMISSION_DETAIL_LOADED'
////// PRESTASI.SUBMISSION-CREATE
export const PRESTASI_PRESTASISUBMISSION_CREATED = 'PRESTASI_PRESTASISUBMISSION_CREATED'